#!/bin/bash
docker volume create --name instant-cache > /dev/null 2>&1docker volume create --name instant-cache > /dev/null 2>&1
docker run -it -p 8888:8888 --rm -v instant-cache:/home/fenics/.instant -v $(pwd):/home/fenics/shared -w /home/fenics/shared quay.io/fenicsproject/stable